! Generated by c68 4.5 27 Feb 99 (Sep  1 2022) from "interrupt.i"
	.sect	.text
	.sect	.rom
	.sect	.data
	.sect	.bss
	.sect	.text
	.align	2
	.extern _disable
_disable:
	trap    #0
        !ori     #0x700,sr
	andi #$07FF,sr
	rts
