! Generated by c68 4.5 27 Feb 99 (Sep  1 2022) from "spritePlot.i"
	.sect	.text
	.sect	.rom
	.sect	.data
	.sect	.bss
	.sect	.text
	.align	2
	.extern _drawSpriteNoMask
_drawSpriteNoMask:
	link	a6,#-12
	movem.l	d3/d4/d5/a2/a3/a4,-(a7)
	move.l	16(a6),a2
	move.l	12(a6),a3
	move.l	20(a6),a4
	move.l	#64,d0
	move.w	6(a4),d1
	ext.l	d1
	sub.l	d1,d0
	move.l	d0,d4
	move.l	8(a6),d0
	sub.l	#4,d0
	beq	I_5
	add.l	#1,d0
	beq	I_6
	add.l	#1,d0
	beq	I_7
	add.l	#1,d0
	beq	I_8
	move.l	#0,d3
	bra	I_26
I_5:
	move.l	#0,d3
	bra	I_10
I_9:
	move.w	(a2)+,d0
	or.w	d0,(a3)+
	move.w	(a2)+,d0
	or.w	d0,(a3)+
	move.w	(a2)+,d0
	or.w	(a2)+,d0
	or.w	d0,(a3)+
	move.w	(a2)+,d0
	or.w	d0,(a3)+
	move.w	(a2)+,d0
	or.w	(a2)+,d0
	or.w	d0,(a3)+
	move.w	(a2)+,d0
	or.w	d0,(a3)+
	move.w	(a2)+,d0
	or.w	(a2)+,d0
	or.w	d0,(a3)+
	move.w	(a2)+,d0
	or.w	d0,(a3)+
	move.w	(a2)+,d0
	or.w	d0,(a3)
	move.l	d4,d0
	add.l	d0,d0
	add.l	d0,a3
	add.l	#1,d3
I_10:
	move.w	4(a4),d0
	ext.l	d0
	cmp.l	d0,d3
	bcs	I_9
	bra	I_27
I_6:
	move.l	#0,d3
	bra	I_14
I_13:
	move.w	(a2)+,d0
	or.w	d0,(a3)+
	move.w	(a2)+,d0
	or.w	d0,(a3)+
	move.w	(a2)+,d0
	or.w	(a2)+,d0
	or.w	d0,(a3)+
	move.w	(a2)+,d0
	or.w	d0,(a3)+
	move.w	(a2)+,d0
	or.w	(a2)+,d0
	or.w	d0,(a3)+
	move.w	(a2)+,d0
	or.w	d0,(a3)+
	move.w	(a2)+,d0
	or.w	d0,(a3)
	move.l	d4,d0
	add.l	d0,d0
	add.l	d0,a3
	add.l	#1,d3
I_14:
	move.w	4(a4),d0
	ext.l	d0
	cmp.l	d0,d3
	bcs	I_13
	bra	I_27
I_7:
	move.l	#0,d3
	bra	I_18
I_17:
	move.w	(a2)+,d0
	or.w	d0,(a3)+
	move.w	(a2)+,d0
	or.w	d0,(a3)+
	move.w	(a2)+,d0
	or.w	(a2)+,d0
	or.w	d0,(a3)+
	move.w	(a2)+,d0
	or.w	d0,(a3)+
	move.w	(a2)+,d0
	or.w	d0,(a3)
	move.l	d4,d0
	add.l	d0,d0
	add.l	d0,a3
	add.l	#1,d3
I_18:
	move.w	4(a4),d0
	ext.l	d0
	cmp.l	d0,d3
	bcs	I_17
	bra	I_27
I_8:
	move.l	#0,d3
	bra	I_22
I_21:
	move.w	(a2)+,d0
	or.w	d0,(a3)+
	move.w	(a2)+,d0
	or.w	d0,(a3)+
	move.w	(a2)+,d0
	or.w	d0,(a3)
	move.l	d4,d0
	add.l	d0,d0
	add.l	d0,a3
	add.l	#1,d3
I_22:
	move.w	4(a4),d0
	ext.l	d0
	cmp.l	d0,d3
	bcs	I_21
	bra	I_27
I_25:
	move.l	#0,d5
	bra	I_30
I_29:
	move.w	(a2)+,d0
	or.w	d0,(a3)+
	move.w	(a2)+,d0
	or.w	d0,(a3)+
	move.w	(a2)+,d0
	or.w	d0,(a3)
	add.l	#1,d5
I_30:
	cmp.l	8(a6),d5
	bcs	I_29
	move.l	d4,d0
	add.l	d0,d0
	add.l	d0,a3
	add.l	#1,d3
I_26:
	move.w	4(a4),d0
	ext.l	d0
	cmp.l	d0,d3
	bcs	I_25
I_27:
	movem.l	(a7)+,d3/d4/d5/a2/a3/a4
	unlk	a6
	rts
